-- ============================================================
-- 电商平台数据库建表脚本 (Oracle 18c+)
-- 说明: 包含24张表，关键字表名加双引号，支持JSON约束
-- 先删除后创建，便于团队同步
-- ============================================================

-- ============================================================
-- 第一步：删除所有表（从依赖最少的子表开始）
-- ============================================================
DECLARE
    PROCEDURE drop_table_if_exists(tbl_name VARCHAR2) IS
        cnt NUMBER;
    BEGIN
        SELECT COUNT(*) INTO cnt FROM user_tables WHERE table_name = UPPER(tbl_name);
        IF cnt > 0 THEN
            EXECUTE IMMEDIATE 'DROP TABLE "' || tbl_name || '" CASCADE CONSTRAINTS PURGE';
        END IF;
    END;
BEGIN
    drop_table_if_exists('ORDER_STAT_SNAPSHOT');
    drop_table_if_exists('OPERATION_LOG');
    drop_table_if_exists('REVIEW');
    drop_table_if_exists('LOGISTICS_TRACK');
    drop_table_if_exists('LOGISTICS');
    drop_table_if_exists('PAYMENT');
    drop_table_if_exists('ORDER_LOG');
    drop_table_if_exists('ORDER_ITEM');
    drop_table_if_exists('ORDER_MAIN');
    drop_table_if_exists('USER_COUPON');
    drop_table_if_exists('COUPON_TEMPLATE');
    drop_table_if_exists('CART');
    drop_table_if_exists('INVENTORY_LOG');
    drop_table_if_exists('SKU');
    drop_table_if_exists('PRODUCT_SPEC');
    drop_table_if_exists('PRODUCT_IMAGE');
    drop_table_if_exists('PRODUCT');
    drop_table_if_exists('CATEGORY');
    drop_table_if_exists('ADDRESS');
    drop_table_if_exists('ROLE_PERMISSION');
    drop_table_if_exists('USER_ROLE');
    drop_table_if_exists('PERMISSION');
    drop_table_if_exists('ROLE');
    drop_table_if_exists('USER');
END;
/

-- ============================================================
-- 第二步：创建表（按依赖顺序，父表先创建）
-- ============================================================

-- 1. user 表（用户表）
CREATE TABLE "USER" (
    id               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (START WITH 10001) PRIMARY KEY,
    username         VARCHAR2(50) NOT NULL,
    password_hash    VARCHAR2(255) NOT NULL,
    phone            VARCHAR2(20),
    email            VARCHAR2(100),
    avatar_url       VARCHAR2(500),
    status           NUMBER(1) DEFAULT 1 NOT NULL,
    created_at       DATE DEFAULT SYSDATE NOT NULL,
    last_login_at    DATE,
    CONSTRAINT uk_user_username UNIQUE (username),
    CONSTRAINT uk_user_phone UNIQUE (phone),
    CONSTRAINT uk_user_email UNIQUE (email),
    CONSTRAINT ch_user_status CHECK (status IN (0,1))
);
COMMENT ON TABLE "USER" IS '用户表';
COMMENT ON COLUMN "USER".id IS '用户ID，自增主键';
COMMENT ON COLUMN "USER".username IS '用户名，唯一';
COMMENT ON COLUMN "USER".password_hash IS '密码加密存储';
COMMENT ON COLUMN "USER".phone IS '手机号，唯一';
COMMENT ON COLUMN "USER".email IS '邮箱，唯一';
COMMENT ON COLUMN "USER".avatar_url IS '头像URL';
COMMENT ON COLUMN "USER".status IS '账号状态：0=禁用，1=正常';
COMMENT ON COLUMN "USER".created_at IS '注册时间';
COMMENT ON COLUMN "USER".last_login_at IS '最后登录时间';

-- 系统后台任务使用该账号写 ORDER_LOG 和 OPERATION_LOG；status=0，不能登录。
INSERT INTO "USER" (id, username, password_hash, status, created_at)
VALUES (1, 'system', 'SYSTEM_ACCOUNT_NOT_FOR_LOGIN', 0, SYSDATE);

-- 2. role 表（角色表）
CREATE TABLE "ROLE" (
    id           NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name    VARCHAR2(50) NOT NULL,
    description  VARCHAR2(200),
    created_at   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uk_role_name UNIQUE (role_name)
);
COMMENT ON TABLE "ROLE" IS '角色表';
COMMENT ON COLUMN "ROLE".id IS '角色ID，自增主键';
COMMENT ON COLUMN "ROLE".role_name IS '角色名称，如ADMIN/USER/SERVICE';
COMMENT ON COLUMN "ROLE".description IS '角色描述';
COMMENT ON COLUMN "ROLE".created_at IS '创建时间';

-- 3. permission 表（权限表）
CREATE TABLE "PERMISSION" (
    id              NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perm_name       VARCHAR2(100) NOT NULL,
    resource_path   VARCHAR2(200) NOT NULL,
    action          VARCHAR2(10) NOT NULL,
    description     VARCHAR2(200),
    CONSTRAINT uk_perm_name UNIQUE (perm_name),
    CONSTRAINT ch_perm_action CHECK (action IN ('GET', 'POST', 'PUT', 'DELETE'))
);
COMMENT ON TABLE "PERMISSION" IS '权限表';
COMMENT ON COLUMN "PERMISSION".id IS '权限ID，自增主键';
COMMENT ON COLUMN "PERMISSION".perm_name IS '权限名称，如订单查看';
COMMENT ON COLUMN "PERMISSION".resource_path IS '资源路径，如/api/v1/orders/**';
COMMENT ON COLUMN "PERMISSION".action IS 'HTTP 方法：GET/POST/PUT/DELETE';
COMMENT ON COLUMN "PERMISSION".description IS '描述';

-- 4. user_role 表（用户角色关联表）
CREATE TABLE USER_ROLE (
    id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      NUMBER(19) NOT NULL,
    role_id      NUMBER(10) NOT NULL,
    assigned_at  DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES "USER"(id),
    CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES "ROLE"(id),
    CONSTRAINT uk_ur_user_role UNIQUE (user_id, role_id)
);
COMMENT ON TABLE USER_ROLE IS '用户角色关联表';
COMMENT ON COLUMN USER_ROLE.id IS '主键，自增';
COMMENT ON COLUMN USER_ROLE.user_id IS '用户ID，外键→user.id';
COMMENT ON COLUMN USER_ROLE.role_id IS '角色ID，外键→role.id';
COMMENT ON COLUMN USER_ROLE.assigned_at IS '分配时间';

-- 5. role_permission 表（角色权限关联表）
CREATE TABLE ROLE_PERMISSION (
    id             NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id        NUMBER(10) NOT NULL,
    permission_id  NUMBER(10) NOT NULL,
    created_at     DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_rp_role FOREIGN KEY (role_id) REFERENCES "ROLE"(id),
    CONSTRAINT fk_rp_permission FOREIGN KEY (permission_id) REFERENCES "PERMISSION"(id),
    CONSTRAINT uk_rp_role_perm UNIQUE (role_id, permission_id)
);
COMMENT ON TABLE ROLE_PERMISSION IS '角色权限关联表';
COMMENT ON COLUMN ROLE_PERMISSION.id IS '主键，自增';
COMMENT ON COLUMN ROLE_PERMISSION.role_id IS '角色ID，外键→role.id';
COMMENT ON COLUMN ROLE_PERMISSION.permission_id IS '权限ID，外键→permission.id';
COMMENT ON COLUMN ROLE_PERMISSION.created_at IS '创建时间';

-- 6. address 表（收货地址表）
CREATE TABLE ADDRESS (
    id               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          NUMBER(19) NOT NULL,
    receiver_name    VARCHAR2(50) NOT NULL,
    receiver_phone   VARCHAR2(20) NOT NULL,
    province         VARCHAR2(50) NOT NULL,
    city             VARCHAR2(50) NOT NULL,
    district         VARCHAR2(50) NOT NULL,
    detail_address   VARCHAR2(500) NOT NULL,
    is_default       NUMBER(1) DEFAULT 0 NOT NULL,
    is_deleted       NUMBER(1) DEFAULT 0 NOT NULL,
    created_at       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_addr_user FOREIGN KEY (user_id) REFERENCES "USER"(id),
    CONSTRAINT ch_addr_default CHECK (is_default IN (0,1)),
    CONSTRAINT ch_addr_deleted CHECK (is_deleted IN (0,1))
);
COMMENT ON TABLE ADDRESS IS '收货地址表';
COMMENT ON COLUMN ADDRESS.id IS '地址ID，自增主键';
COMMENT ON COLUMN ADDRESS.user_id IS '用户ID，外键→user.id';
COMMENT ON COLUMN ADDRESS.receiver_name IS '收货人姓名';
COMMENT ON COLUMN ADDRESS.receiver_phone IS '收货人手机号';
COMMENT ON COLUMN ADDRESS.province IS '省';
COMMENT ON COLUMN ADDRESS.city IS '市';
COMMENT ON COLUMN ADDRESS.district IS '区/县';
COMMENT ON COLUMN ADDRESS.detail_address IS '详细地址';
COMMENT ON COLUMN ADDRESS.is_default IS '是否默认：0=否，1=是';
COMMENT ON COLUMN ADDRESS.is_deleted IS '软删除标记：0=有效，1=已删除';
COMMENT ON COLUMN ADDRESS.created_at IS '创建时间';

-- 7. category 表（商品分类表）
CREATE TABLE "CATEGORY" (
    id           NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id    NUMBER(10),
    name         VARCHAR2(100) NOT NULL,
    tree_level   NUMBER(1) NOT NULL,
    sort_order   NUMBER(10) DEFAULT 0,
    status       NUMBER(1) DEFAULT 1 NOT NULL,
    icon_url     VARCHAR2(500),
    created_at   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_cat_parent FOREIGN KEY (parent_id) REFERENCES "CATEGORY"(id),
    CONSTRAINT ch_cat_level CHECK (tree_level BETWEEN 1 AND 5),
    CONSTRAINT ch_cat_status CHECK (status IN (0,1))
);
COMMENT ON TABLE "CATEGORY" IS '商品分类表';
COMMENT ON COLUMN "CATEGORY".id IS '分类ID，自增主键';
COMMENT ON COLUMN "CATEGORY".parent_id IS '父分类ID，根节点为NULL';
COMMENT ON COLUMN "CATEGORY".name IS '分类名称';
COMMENT ON COLUMN "CATEGORY".tree_level IS '层级：1=一级，2=二级';
COMMENT ON COLUMN "CATEGORY".sort_order IS '排序序号，数值越小越靠前';
COMMENT ON COLUMN "CATEGORY".status IS '状态：0=禁用，1=启用';
COMMENT ON COLUMN "CATEGORY".icon_url IS '分类图标URL';
COMMENT ON COLUMN "CATEGORY".created_at IS '创建时间';

-- 8. product 表（商品主表）
CREATE TABLE PRODUCT (
    id            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id   NUMBER(10) NOT NULL,
    name          VARCHAR2(200) NOT NULL,
    description   CLOB,
    main_image    VARCHAR2(500) NOT NULL,
    status        NUMBER(1) DEFAULT 1 NOT NULL,
    price_min     NUMBER(10,2) NOT NULL,
    sales_count   NUMBER(10) DEFAULT 0 NOT NULL,
    view_count    NUMBER(10) DEFAULT 0 NOT NULL,
    avg_rating    NUMBER(3,2) DEFAULT 0.00,
    created_at    DATE DEFAULT SYSDATE NOT NULL,
    updated_at    DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_prod_category FOREIGN KEY (category_id) REFERENCES "CATEGORY"(id),
    CONSTRAINT ch_prod_status CHECK (status IN (0,1,2))
);
COMMENT ON TABLE PRODUCT IS '商品主表';
COMMENT ON COLUMN PRODUCT.id IS '商品ID，自增主键';
COMMENT ON COLUMN PRODUCT.category_id IS '分类ID，外键→category.id';
COMMENT ON COLUMN PRODUCT.name IS '商品名称';
COMMENT ON COLUMN PRODUCT.description IS '商品描述，富文本';
COMMENT ON COLUMN PRODUCT.main_image IS '主图URL';
COMMENT ON COLUMN PRODUCT.status IS '上架状态：0=下架，1=上架，2=预售';
COMMENT ON COLUMN PRODUCT.price_min IS '最低售价（冗余），取自各SKU最低价';
COMMENT ON COLUMN PRODUCT.sales_count IS '累计销量';
COMMENT ON COLUMN PRODUCT.view_count IS '浏览量';
COMMENT ON COLUMN PRODUCT.avg_rating IS '评分均值';
COMMENT ON COLUMN PRODUCT.created_at IS '创建时间';
COMMENT ON COLUMN PRODUCT.updated_at IS '更新时间';

-- 9. product_image 表（商品图片表）
CREATE TABLE PRODUCT_IMAGE (
    id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   NUMBER(19) NOT NULL,
    image_url    VARCHAR2(500) NOT NULL,
    sort_order   NUMBER(10) DEFAULT 0,
    created_at   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_pi_product FOREIGN KEY (product_id) REFERENCES PRODUCT(id)
);
COMMENT ON TABLE PRODUCT_IMAGE IS '商品图片表';
COMMENT ON COLUMN PRODUCT_IMAGE.id IS '图片ID，自增主键';
COMMENT ON COLUMN PRODUCT_IMAGE.product_id IS '商品ID，外键→product.id';
COMMENT ON COLUMN PRODUCT_IMAGE.image_url IS '图片URL';
COMMENT ON COLUMN PRODUCT_IMAGE.sort_order IS '排序序号，数值越小越靠前';
COMMENT ON COLUMN PRODUCT_IMAGE.created_at IS '创建时间';

-- 10. product_spec 表（商品规格表）
CREATE TABLE PRODUCT_SPEC (
    id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   NUMBER(19) NOT NULL,
    spec_name    VARCHAR2(100) NOT NULL,
    spec_value   VARCHAR2(200) NOT NULL,
    sort_order   NUMBER(10) DEFAULT 0,
    created_at   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_ps_product FOREIGN KEY (product_id) REFERENCES PRODUCT(id)
);
COMMENT ON TABLE PRODUCT_SPEC IS '商品规格表';
COMMENT ON COLUMN PRODUCT_SPEC.id IS '规格ID，自增主键';
COMMENT ON COLUMN PRODUCT_SPEC.product_id IS '商品ID，外键→product.id';
COMMENT ON COLUMN PRODUCT_SPEC.spec_name IS '规格名称，如颜色、尺码';
COMMENT ON COLUMN PRODUCT_SPEC.spec_value IS '规格值，如红色、M码';
COMMENT ON COLUMN PRODUCT_SPEC.sort_order IS '排序序号，同一规格名下的选项排序';
COMMENT ON COLUMN PRODUCT_SPEC.created_at IS '创建时间';

-- 11. sku 表（商品SKU表）
CREATE TABLE SKU (
    id               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id       NUMBER(19) NOT NULL,
    spec_desc        VARCHAR2(4000) NOT NULL,
    price            NUMBER(10,2) NOT NULL,
    original_price   NUMBER(10,2),
    stock            NUMBER(10) NOT NULL,
    locked_stock     NUMBER(10) DEFAULT 0 NOT NULL,
    warning_stock    NUMBER(10) DEFAULT 0 NOT NULL,
    sku_image        VARCHAR2(500),
    status           NUMBER(1) DEFAULT 1 NOT NULL,
    created_at       DATE DEFAULT SYSDATE NOT NULL,
    updated_at       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_sku_product FOREIGN KEY (product_id) REFERENCES PRODUCT(id),
    CONSTRAINT ch_sku_spec_desc_json CHECK (spec_desc IS JSON),
    CONSTRAINT ch_sku_status CHECK (status IN (0,1)),
    CONSTRAINT uk_sku_product_spec UNIQUE (product_id, spec_desc),
    CONSTRAINT ch_sku_stock_nonnegative CHECK (stock >= 0),
    CONSTRAINT ch_sku_locked_stock_nonnegative CHECK (locked_stock >= 0),
    CONSTRAINT ch_sku_stock_not_below_locked CHECK (stock >= locked_stock)
);
COMMENT ON TABLE SKU IS '商品SKU表';
COMMENT ON COLUMN SKU.id IS 'SKU ID，自增主键';
COMMENT ON COLUMN SKU.product_id IS '商品ID，外键→product.id';
COMMENT ON COLUMN SKU.spec_desc IS '规格描述，JSON格式，如{"颜色":"红色","尺码":"M"}';
COMMENT ON COLUMN SKU.price IS '售价';
COMMENT ON COLUMN SKU.original_price IS '原价（划线价）';
COMMENT ON COLUMN SKU.stock IS '实际库存';
COMMENT ON COLUMN SKU.locked_stock IS '锁定库存（已下单未支付）';
COMMENT ON COLUMN SKU.warning_stock IS '预警库存阈值';
COMMENT ON COLUMN SKU.sku_image IS 'SKU图片URL';
COMMENT ON COLUMN SKU.status IS '状态：0=停售，1=在售';
COMMENT ON COLUMN SKU.created_at IS '创建时间';
COMMENT ON COLUMN SKU.updated_at IS '更新时间';

-- 12. inventory_log 表（库存变动日志表）
CREATE TABLE INVENTORY_LOG (
    id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id         NUMBER(19) NOT NULL,
    change_type    VARCHAR2(30) NOT NULL,
    change_qty     NUMBER(10) NOT NULL,
    before_stock   NUMBER(10) NOT NULL,
    after_stock    NUMBER(10) NOT NULL,
    operator_id    NUMBER(19),
    ref_order_id   NUMBER(19),
    remark         VARCHAR2(500),
    created_at     DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_ilog_sku FOREIGN KEY (sku_id) REFERENCES SKU(id),
    CONSTRAINT fk_ilog_operator FOREIGN KEY (operator_id) REFERENCES "USER"(id),
    CONSTRAINT ch_ilog_type CHECK (change_type IN ('SALE','CANCEL','RESTOCK','ADJUST','ORDER_LOCK','ORDER_RELEASE','ORDER_DEDUCT'))
);
COMMENT ON TABLE INVENTORY_LOG IS '库存变动日志表';
COMMENT ON COLUMN INVENTORY_LOG.id IS '日志ID，自增主键';
COMMENT ON COLUMN INVENTORY_LOG.sku_id IS 'SKU ID，外键→sku.id';
COMMENT ON COLUMN INVENTORY_LOG.change_type IS '变动类型：SALE/CANCEL/RESTOCK/ADJUST/ORDER_LOCK/ORDER_RELEASE/ORDER_DEDUCT';
COMMENT ON COLUMN INVENTORY_LOG.change_qty IS '变动数量，正数入库，负数出库';
COMMENT ON COLUMN INVENTORY_LOG.before_stock IS '变动前库存';
COMMENT ON COLUMN INVENTORY_LOG.after_stock IS '变动后库存';
COMMENT ON COLUMN INVENTORY_LOG.operator_id IS '操作人ID，外键→user.id，系统自动操作时为NULL';
COMMENT ON COLUMN INVENTORY_LOG.ref_order_id IS '关联订单ID，可空';
COMMENT ON COLUMN INVENTORY_LOG.remark IS '备注';
COMMENT ON COLUMN INVENTORY_LOG.created_at IS '操作时间';

-- 13. cart 表（购物车表）
CREATE TABLE CART (
    id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      NUMBER(19) NOT NULL,
    sku_id       NUMBER(19) NOT NULL,
    quantity     NUMBER(10) NOT NULL,
    selected     NUMBER(1) DEFAULT 1 NOT NULL,
    created_at   DATE DEFAULT SYSDATE NOT NULL,
    updated_at   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES "USER"(id),
    CONSTRAINT fk_cart_sku FOREIGN KEY (sku_id) REFERENCES SKU(id),
    CONSTRAINT ch_cart_selected CHECK (selected IN (0,1)),
    CONSTRAINT ch_cart_quantity CHECK (quantity > 0),
    CONSTRAINT uk_cart_user_sku UNIQUE (user_id, sku_id)
);
COMMENT ON TABLE CART IS '购物车表';
COMMENT ON COLUMN CART.id IS '购物车ID，自增主键';
COMMENT ON COLUMN CART.user_id IS '用户ID，外键→user.id';
COMMENT ON COLUMN CART.sku_id IS 'SKU ID，外键→sku.id';
COMMENT ON COLUMN CART.quantity IS '数量';
COMMENT ON COLUMN CART.selected IS '是否选中：0=未勾选，1=已勾选';
COMMENT ON COLUMN CART.created_at IS '加入时间';
COMMENT ON COLUMN CART.updated_at IS '更新时间';

-- 14. coupon_template 表（优惠券模板表）
CREATE TABLE COUPON_TEMPLATE (
    id               NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR2(100) NOT NULL,
    type             NUMBER(1) NOT NULL,
    amount           NUMBER(10,2) NOT NULL,
    min_amount       NUMBER(10,2) NOT NULL,
    total_count      NUMBER(10) NOT NULL,
    received_count   NUMBER(10) DEFAULT 0 NOT NULL,
    start_time       DATE NOT NULL,
    end_time         DATE NOT NULL,
    status           NUMBER(1) DEFAULT 1 NOT NULL,
    applicable_category_id NUMBER(10),
    CONSTRAINT fk_coup_category FOREIGN KEY (applicable_category_id) REFERENCES "CATEGORY"(id),
    CONSTRAINT ch_coup_type CHECK (type IN (1,2)),
    CONSTRAINT ch_coup_status CHECK (status IN (0,1)),
    CONSTRAINT ch_coup_time CHECK (end_time > start_time),
    CONSTRAINT ch_coup_amount CHECK ((type = 1 AND amount > 0 AND min_amount >= amount) OR (type = 2 AND amount > 0 AND amount <= 1)),
    CONSTRAINT ch_coup_min_amount CHECK (min_amount >= 0),
    CONSTRAINT ch_coup_total CHECK (total_count = -1 OR total_count >= 0),
    CONSTRAINT ch_coup_received CHECK (received_count >= 0 AND (total_count = -1 OR received_count <= total_count))
);
COMMENT ON TABLE COUPON_TEMPLATE IS '优惠券模板表';
COMMENT ON COLUMN COUPON_TEMPLATE.id IS '券模板ID，自增主键';
COMMENT ON COLUMN COUPON_TEMPLATE.name IS '优惠券名称';
COMMENT ON COLUMN COUPON_TEMPLATE.type IS '类型：1=满减券，2=折扣券';
COMMENT ON COLUMN COUPON_TEMPLATE.amount IS '面值（满减券）或折扣率（折扣券如0.85）';
COMMENT ON COLUMN COUPON_TEMPLATE.min_amount IS '最低消费门槛';
COMMENT ON COLUMN COUPON_TEMPLATE.total_count IS '发行总量，-1表示不限量';
COMMENT ON COLUMN COUPON_TEMPLATE.received_count IS '已领取数量';
COMMENT ON COLUMN COUPON_TEMPLATE.start_time IS '有效期开始';
COMMENT ON COLUMN COUPON_TEMPLATE.end_time IS '有效期结束';
COMMENT ON COLUMN COUPON_TEMPLATE.status IS '状态：0=停用，1=启用';
COMMENT ON COLUMN COUPON_TEMPLATE.applicable_category_id IS '适用的末级商品分类ID，NULL表示全场通用';

-- 15. user_coupon 表（用户优惠券表）
CREATE TABLE USER_COUPON (
    id                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             NUMBER(19) NOT NULL,
    coupon_template_id  NUMBER(10) NOT NULL,
    status              NUMBER(1) DEFAULT 0 NOT NULL,
    received_at         DATE DEFAULT SYSDATE NOT NULL,
    used_at             DATE,
    order_id            NUMBER(19),
    CONSTRAINT fk_uc_user FOREIGN KEY (user_id) REFERENCES "USER"(id),
    CONSTRAINT fk_uc_template FOREIGN KEY (coupon_template_id) REFERENCES COUPON_TEMPLATE(id),
    CONSTRAINT uk_uc_user_template UNIQUE (user_id, coupon_template_id),
    CONSTRAINT ch_uc_status CHECK (status IN (0,1,2))
);
COMMENT ON TABLE USER_COUPON IS '用户优惠券表';
COMMENT ON COLUMN USER_COUPON.id IS '领取ID，自增主键';
COMMENT ON COLUMN USER_COUPON.user_id IS '用户ID，外键→user.id';
COMMENT ON COLUMN USER_COUPON.coupon_template_id IS '券模板ID，外键→coupon_template.id';
COMMENT ON COLUMN USER_COUPON.status IS '使用状态：0=未使用，1=已使用，2=已过期';
COMMENT ON COLUMN USER_COUPON.received_at IS '领取时间';
COMMENT ON COLUMN USER_COUPON.used_at IS '使用时间';
COMMENT ON COLUMN USER_COUPON.order_id IS '关联订单ID';

-- 16. order_main 表（订单主表）
CREATE TABLE ORDER_MAIN (
    id                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no            VARCHAR2(32) NOT NULL,
    user_id             NUMBER(19) NOT NULL,
    address_id          NUMBER(19) NOT NULL,
    user_coupon_id      NUMBER(19),
    status              NUMBER(1) DEFAULT 0 NOT NULL,
    total_amount        NUMBER(10,2) NOT NULL,
    discount_amount     NUMBER(10,2) DEFAULT 0 NOT NULL,
    pay_amount          NUMBER(10,2) NOT NULL,
    pay_expire_time     DATE NOT NULL,
    receiver_snapshot   VARCHAR2(4000) NOT NULL,
    remark              VARCHAR2(500),
    created_at          DATE DEFAULT SYSDATE NOT NULL,
    updated_at          DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_om_user FOREIGN KEY (user_id) REFERENCES "USER"(id),
    CONSTRAINT fk_om_address FOREIGN KEY (address_id) REFERENCES ADDRESS(id),
    CONSTRAINT fk_om_coupon FOREIGN KEY (user_coupon_id) REFERENCES USER_COUPON(id),
    CONSTRAINT uk_om_order_no UNIQUE (order_no),
    CONSTRAINT ch_om_status CHECK (status IN (0,1,2,3,4)),
    CONSTRAINT ch_om_amount_consistency CHECK (
        total_amount >= 0
        AND discount_amount >= 0
        AND discount_amount <= total_amount
        AND pay_amount >= 0
        AND (
            (status = 4 AND pay_amount = 0)
            OR (status IN (0,1,2,3) AND pay_amount = total_amount - discount_amount)
        )
    ),
    CONSTRAINT ch_om_receiver_json CHECK (receiver_snapshot IS JSON)
);
COMMENT ON TABLE ORDER_MAIN IS '订单主表';
COMMENT ON COLUMN ORDER_MAIN.id IS '订单ID，自增主键';
COMMENT ON COLUMN ORDER_MAIN.order_no IS '订单编号，业务唯一标识';
COMMENT ON COLUMN ORDER_MAIN.user_id IS '用户ID，外键→user.id';
COMMENT ON COLUMN ORDER_MAIN.address_id IS '收货地址ID，外键→address.id';
COMMENT ON COLUMN ORDER_MAIN.user_coupon_id IS '优惠券领取ID，外键→user_coupon.id，未用券时为NULL';
COMMENT ON COLUMN ORDER_MAIN.status IS '订单状态：0待支付，1已支付，2已发货，3已完成，4已取消';
COMMENT ON COLUMN ORDER_MAIN.total_amount IS '商品总额';
COMMENT ON COLUMN ORDER_MAIN.discount_amount IS '优惠金额';
COMMENT ON COLUMN ORDER_MAIN.pay_amount IS '待支付或实际支付金额；已取消订单必须为0';
COMMENT ON COLUMN ORDER_MAIN.pay_expire_time IS '支付超时时间';
COMMENT ON COLUMN ORDER_MAIN.receiver_snapshot IS '收货人快照，JSON格式';
COMMENT ON COLUMN ORDER_MAIN.remark IS '买家备注';
COMMENT ON COLUMN ORDER_MAIN.created_at IS '创建时间';
COMMENT ON COLUMN ORDER_MAIN.updated_at IS '更新时间';

-- 17. order_item 表（订单明细表）
CREATE TABLE ORDER_ITEM (
    id                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id           NUMBER(19) NOT NULL,
    sku_id             NUMBER(19) NOT NULL,
    product_name_snap  VARCHAR2(200) NOT NULL,
    spec_snap          VARCHAR2(500) NOT NULL,
    main_image_snap    VARCHAR2(500) NOT NULL,
    unit_price         NUMBER(10,2) NOT NULL,
    quantity           NUMBER(10) NOT NULL,
    subtotal           NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_oi_order FOREIGN KEY (order_id) REFERENCES ORDER_MAIN(id),
    CONSTRAINT fk_oi_sku FOREIGN KEY (sku_id) REFERENCES SKU(id),
    CONSTRAINT ch_order_item_quantity CHECK (quantity > 0),
    CONSTRAINT ch_order_item_amount CHECK (unit_price >= 0 AND subtotal = unit_price * quantity)
);
COMMENT ON TABLE ORDER_ITEM IS '订单明细表';
COMMENT ON COLUMN ORDER_ITEM.id IS '明细ID，自增主键';
COMMENT ON COLUMN ORDER_ITEM.order_id IS '订单ID，外键→order_main.id';
COMMENT ON COLUMN ORDER_ITEM.sku_id IS 'SKU ID，外键→sku.id';
COMMENT ON COLUMN ORDER_ITEM.product_name_snap IS '商品名称快照';
COMMENT ON COLUMN ORDER_ITEM.spec_snap IS '规格快照';
COMMENT ON COLUMN ORDER_ITEM.main_image_snap IS '商品主图快照';
COMMENT ON COLUMN ORDER_ITEM.unit_price IS '下单单价快照';
COMMENT ON COLUMN ORDER_ITEM.quantity IS '购买数量';
COMMENT ON COLUMN ORDER_ITEM.subtotal IS '小计金额';

-- 18. order_log 表（订单状态日志表）
CREATE TABLE ORDER_LOG (
    id            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      NUMBER(19) NOT NULL,
    from_status   NUMBER(1),
    to_status     NUMBER(1) NOT NULL,
    operator_id   NUMBER(19),
    operator_name VARCHAR2(50),
    remark        VARCHAR2(200),
    created_at    DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_olog_order FOREIGN KEY (order_id) REFERENCES ORDER_MAIN(id),
    CONSTRAINT fk_olog_operator FOREIGN KEY (operator_id) REFERENCES "USER"(id)
);
COMMENT ON TABLE ORDER_LOG IS '订单状态日志表';
COMMENT ON COLUMN ORDER_LOG.id IS '日志ID，自增主键';
COMMENT ON COLUMN ORDER_LOG.order_id IS '订单ID，外键→order_main.id';
COMMENT ON COLUMN ORDER_LOG.from_status IS '变更前状态';
COMMENT ON COLUMN ORDER_LOG.to_status IS '变更后状态';
COMMENT ON COLUMN ORDER_LOG.operator_id IS '操作人ID，外键→user.id，系统操作时为NULL';
COMMENT ON COLUMN ORDER_LOG.operator_name IS '操作人用户名快照，系统操作时为NULL';
COMMENT ON COLUMN ORDER_LOG.remark IS '备注';
COMMENT ON COLUMN ORDER_LOG.created_at IS '变更时间';

-- 19. payment 表（支付记录表）
CREATE TABLE PAYMENT (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        NUMBER(19) NOT NULL,
    pay_method      VARCHAR2(30) NOT NULL,
    status          NUMBER(1) DEFAULT 0 NOT NULL,
    trade_no        VARCHAR2(100),
    pay_amount      NUMBER(10,2) NOT NULL,
    paid_at         DATE,
    callback_data   CLOB,
    CONSTRAINT fk_pay_order FOREIGN KEY (order_id) REFERENCES ORDER_MAIN(id),
    CONSTRAINT uk_pay_order UNIQUE (order_id),
    CONSTRAINT ch_pay_status CHECK (status IN (0,1,2,3)),
    CONSTRAINT ch_pay_amount_nonnegative CHECK (pay_amount >= 0),
    CONSTRAINT ch_pay_paid_at CHECK (
        (status IN (0,2) AND paid_at IS NULL)
        OR (status IN (1,3) AND paid_at IS NOT NULL)
    ),
    CONSTRAINT ch_pay_trade_no CHECK (
        status IN (0,2) OR trade_no IS NOT NULL
    )
);
COMMENT ON TABLE PAYMENT IS '支付记录表';
COMMENT ON COLUMN PAYMENT.id IS '支付ID，自增主键';
COMMENT ON COLUMN PAYMENT.order_id IS '订单ID，外键→order_main.id，唯一';
COMMENT ON COLUMN PAYMENT.pay_method IS '支付方式：支付宝、微信支付、模拟支付';
COMMENT ON COLUMN PAYMENT.status IS '支付状态：0待支付，1支付成功，2支付失败，3已退款';
COMMENT ON COLUMN PAYMENT.trade_no IS '第三方交易流水号';
COMMENT ON COLUMN PAYMENT.pay_amount IS '实付金额';
COMMENT ON COLUMN PAYMENT.paid_at IS '支付时间';
COMMENT ON COLUMN PAYMENT.callback_data IS '回调原始数据，用于对账';

-- 20. logistics 表（物流信息表）
CREATE TABLE LOGISTICS (
    id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       NUMBER(19) NOT NULL,
    company_name   VARCHAR2(100) NOT NULL,
    tracking_no    VARCHAR2(100) NOT NULL,
    shipped_at     DATE,
    status         NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_log_order FOREIGN KEY (order_id) REFERENCES ORDER_MAIN(id),
    CONSTRAINT uk_log_order UNIQUE (order_id),
    CONSTRAINT uk_log_tracking_no UNIQUE (tracking_no),
    CONSTRAINT ch_log_status CHECK (status IN (0,1,2,3))
);
COMMENT ON TABLE LOGISTICS IS '物流信息表';
COMMENT ON COLUMN LOGISTICS.id IS '物流ID，自增主键';
COMMENT ON COLUMN LOGISTICS.order_id IS '订单ID，外键→order_main.id，唯一';
COMMENT ON COLUMN LOGISTICS.company_name IS '物流公司名称';
COMMENT ON COLUMN LOGISTICS.tracking_no IS '运单号，唯一';
COMMENT ON COLUMN LOGISTICS.shipped_at IS '发货时间';
COMMENT ON COLUMN LOGISTICS.status IS '物流状态：0已揽件，1运输中，2派件中，3已签收';

-- 21. logistics_track 表（物流轨迹表）
CREATE TABLE LOGISTICS_TRACK (
    id            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logistics_id  NUMBER(19) NOT NULL,
    track_desc    VARCHAR2(500) NOT NULL,
    track_time    DATE NOT NULL,
    location      VARCHAR2(200),
    CONSTRAINT fk_lt_logistics FOREIGN KEY (logistics_id) REFERENCES LOGISTICS(id)
);
COMMENT ON TABLE LOGISTICS_TRACK IS '物流轨迹表';
COMMENT ON COLUMN LOGISTICS_TRACK.id IS '轨迹ID，自增主键';
COMMENT ON COLUMN LOGISTICS_TRACK.logistics_id IS '物流ID，外键→logistics.id';
COMMENT ON COLUMN LOGISTICS_TRACK.track_desc IS '轨迹描述';
COMMENT ON COLUMN LOGISTICS_TRACK.track_time IS '轨迹时间';
COMMENT ON COLUMN LOGISTICS_TRACK.location IS '所在地';

-- 22. review 表（商品评价表）
CREATE TABLE REVIEW (
    id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       NUMBER(19) NOT NULL,
    product_id     NUMBER(19) NOT NULL,
    user_id        NUMBER(19) NOT NULL,
    rating         NUMBER(1) NOT NULL,
    content        CLOB,
    images         VARCHAR2(2000),
    is_anonymous   NUMBER(1) DEFAULT 0 NOT NULL,
    status         NUMBER(1) DEFAULT 0 NOT NULL,
    created_at     DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_rev_order FOREIGN KEY (order_id) REFERENCES ORDER_MAIN(id),
    CONSTRAINT fk_rev_product FOREIGN KEY (product_id) REFERENCES PRODUCT(id),
    CONSTRAINT fk_rev_user FOREIGN KEY (user_id) REFERENCES "USER"(id),
    CONSTRAINT uk_review_order_product_user UNIQUE (order_id, product_id, user_id),
    CONSTRAINT ch_rev_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT ch_rev_anonymous CHECK (is_anonymous IN (0,1)),
    CONSTRAINT ch_rev_status CHECK (status IN (0,1,2)),
    CONSTRAINT ch_rev_images_json CHECK (images IS JSON)
);
COMMENT ON TABLE REVIEW IS '商品评价表';
COMMENT ON COLUMN REVIEW.id IS '评价ID，自增主键';
COMMENT ON COLUMN REVIEW.order_id IS '订单ID，外键→order_main.id';
COMMENT ON COLUMN REVIEW.product_id IS '商品ID，外键→product.id';
COMMENT ON COLUMN REVIEW.user_id IS '用户ID，外键→user.id';
COMMENT ON COLUMN REVIEW.rating IS '评分：1~5星';
COMMENT ON COLUMN REVIEW.content IS '评价内容';
COMMENT ON COLUMN REVIEW.images IS '评价图片URL列表，JSON数组';
COMMENT ON COLUMN REVIEW.is_anonymous IS '是否匿名：0=显示用户名，1=匿名';
COMMENT ON COLUMN REVIEW.status IS '状态：0审核中，1已发布，2已屏蔽';
COMMENT ON COLUMN REVIEW.created_at IS '评价时间';

-- 23. operation_log 表（操作日志表）
CREATE TABLE OPERATION_LOG (
    id               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id      NUMBER(19) NOT NULL,
    operator_name    VARCHAR2(50) NOT NULL,
    module           VARCHAR2(50) NOT NULL,
    action           VARCHAR2(100) NOT NULL,
    description      CLOB,
    ip_address       VARCHAR2(50) NOT NULL,
    request_params   CLOB,
    result           NUMBER(1) DEFAULT 1 NOT NULL,
    created_at       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_oplog_user FOREIGN KEY (operator_id) REFERENCES "USER"(id),
    CONSTRAINT ch_oplog_result CHECK (result IN (0,1))
);
COMMENT ON TABLE OPERATION_LOG IS '操作日志表';
COMMENT ON COLUMN OPERATION_LOG.id IS '日志ID，自增主键';
COMMENT ON COLUMN OPERATION_LOG.operator_id IS '操作员ID，外键→user.id';
COMMENT ON COLUMN OPERATION_LOG.operator_name IS '操作员用户名（冗余）';
COMMENT ON COLUMN OPERATION_LOG.module IS '操作模块，如商品管理';
COMMENT ON COLUMN OPERATION_LOG.action IS '操作动作，如修改商品价格';
COMMENT ON COLUMN OPERATION_LOG.description IS '操作详情';
COMMENT ON COLUMN OPERATION_LOG.ip_address IS '操作者IP地址';
COMMENT ON COLUMN OPERATION_LOG.request_params IS '请求参数（脱敏后），JSON格式';
COMMENT ON COLUMN OPERATION_LOG.result IS '操作结果：0=失败，1=成功';
COMMENT ON COLUMN OPERATION_LOG.created_at IS '操作时间';

-- 24. order_stat_snapshot 表（订单统计快照表）
CREATE TABLE ORDER_STAT_SNAPSHOT (
    id                NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stat_date         DATE NOT NULL,
    order_count       NUMBER(10) DEFAULT 0 NOT NULL,
    paid_count        NUMBER(10) DEFAULT 0 NOT NULL,
    sales_amount      NUMBER(12,2) DEFAULT 0 NOT NULL,
    refund_amount     NUMBER(12,2) DEFAULT 0 NOT NULL,
    avg_order_amount  NUMBER(10,2) DEFAULT 0 NOT NULL,
    new_user_count    NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT uk_stat_date UNIQUE (stat_date)
);
COMMENT ON TABLE ORDER_STAT_SNAPSHOT IS '订单统计快照表';
COMMENT ON COLUMN ORDER_STAT_SNAPSHOT.id IS 'ID，自增主键';
COMMENT ON COLUMN ORDER_STAT_SNAPSHOT.stat_date IS '统计日期，唯一';
COMMENT ON COLUMN ORDER_STAT_SNAPSHOT.order_count IS '当日订单总数';
COMMENT ON COLUMN ORDER_STAT_SNAPSHOT.paid_count IS '当日已支付订单数';
COMMENT ON COLUMN ORDER_STAT_SNAPSHOT.sales_amount IS '当日销售额';
COMMENT ON COLUMN ORDER_STAT_SNAPSHOT.refund_amount IS '当日退款金额，当前退款流程未实现，快照写0并预留扩展';
COMMENT ON COLUMN ORDER_STAT_SNAPSHOT.avg_order_amount IS '客单价';
COMMENT ON COLUMN ORDER_STAT_SNAPSHOT.new_user_count IS '当日新增用户数';

-- ============================================================
-- 可选：为常用查询字段创建索引（提升性能）
-- ============================================================
CREATE INDEX idx_address_user_id ON ADDRESS(user_id);
-- Oracle 的函数索引只在“有效且默认”时产生键值，从数据库层保证每个用户至多一个默认地址。
CREATE UNIQUE INDEX uk_address_one_default ON ADDRESS (
    CASE WHEN is_deleted = 0 AND is_default = 1 THEN user_id END
);
CREATE INDEX idx_product_category ON PRODUCT(category_id);
CREATE INDEX idx_product_status ON PRODUCT(status);
CREATE INDEX idx_sku_product ON SKU(product_id);
CREATE INDEX idx_inventory_log_sku ON INVENTORY_LOG(sku_id);
CREATE INDEX idx_inventory_log_created ON INVENTORY_LOG(created_at);
CREATE INDEX idx_cart_user ON CART(user_id);
CREATE INDEX idx_order_main_user_id ON ORDER_MAIN(user_id);
CREATE INDEX idx_order_main_status ON ORDER_MAIN(status);
CREATE INDEX idx_order_main_created ON ORDER_MAIN(created_at);
CREATE INDEX idx_order_main_pay_expire ON ORDER_MAIN(pay_expire_time, status);
CREATE INDEX idx_order_item_order ON ORDER_ITEM(order_id);
CREATE INDEX idx_order_log_order ON ORDER_LOG(order_id);
CREATE INDEX idx_logistics_track_logistics ON LOGISTICS_TRACK(logistics_id);
CREATE INDEX idx_review_product ON REVIEW(product_id);
CREATE INDEX idx_review_user ON REVIEW(user_id);
CREATE INDEX idx_operation_log_operator ON OPERATION_LOG(operator_id);
CREATE INDEX idx_operation_log_created ON OPERATION_LOG(created_at);
CREATE INDEX idx_user_coupon_user ON USER_COUPON(user_id);
CREATE INDEX idx_user_coupon_status ON USER_COUPON(status);

COMMIT;
