-- ======================================================
-- 电商平台数据库建表脚本（Oracle 版）
-- 说明: 基于《电商平台数据库设计说明书.docx》转换
-- 适用: Oracle 12c 及以上（使用 IDENTITY 列）
-- ======================================================

-- 删除表（按依赖倒序，使用 CASCADE CONSTRAINTS 处理外键）
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE order_stat_snapshot CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE operation_log CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE review CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE logistics_track CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE logistics CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE payment CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE order_log CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE order_item CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE order_main CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE user_coupon CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE role_permission CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE user_role CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE cart CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE inventory_log CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE sku CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE product_spec CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE product_image CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE product CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE category CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE address CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE coupon_template CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE permission CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE role CASCADE CONSTRAINTS PURGE';
    EXECUTE IMMEDIATE 'DROP TABLE "user" CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- 1. 用户表
CREATE TABLE "user" (
    id              NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR2(50)    NOT NULL,
    password_hash   VARCHAR2(255)   NOT NULL,
    phone           VARCHAR2(20),
    email           VARCHAR2(100),
    avatar_url      VARCHAR2(500),
    status          NUMBER(1)       DEFAULT 1 NOT NULL,
    created_at      DATE            DEFAULT SYSDATE NOT NULL,
    last_login_at   DATE,
    CONSTRAINT uk_user_username UNIQUE (username),
    CONSTRAINT uk_user_phone UNIQUE (phone),
    CONSTRAINT uk_user_email UNIQUE (email)
);
COMMENT ON TABLE "user" IS '用户表';
COMMENT ON COLUMN "user".id IS '用户ID';
COMMENT ON COLUMN "user".username IS '用户名';
COMMENT ON COLUMN "user".password_hash IS '密码（加密存储）';
COMMENT ON COLUMN "user".phone IS '手机号';
COMMENT ON COLUMN "user".email IS '邮箱';
COMMENT ON COLUMN "user".avatar_url IS '头像URL';
COMMENT ON COLUMN "user".status IS '账号状态 0=禁用 1=正常';
COMMENT ON COLUMN "user".created_at IS '注册时间';
COMMENT ON COLUMN "user".last_login_at IS '最后登录时间';

-- 2. 角色表
CREATE TABLE role (
    id          NUMBER(11)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name   VARCHAR2(50)    NOT NULL,
    description VARCHAR2(200),
    created_at  DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uk_role_name UNIQUE (role_name)
);
COMMENT ON TABLE role IS '角色表';
COMMENT ON COLUMN role.id IS '角色ID';
COMMENT ON COLUMN role.role_name IS '角色名称';
COMMENT ON COLUMN role.description IS '角色描述';
COMMENT ON COLUMN role.created_at IS '创建时间';

-- 3. 权限表
CREATE TABLE permission (
    id            NUMBER(11)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perm_name     VARCHAR2(100)   NOT NULL,
    resource_path VARCHAR2(200),
    action        VARCHAR2(20),
    description   VARCHAR2(200)
);
COMMENT ON TABLE permission IS '权限表';
COMMENT ON COLUMN permission.id IS '权限ID';
COMMENT ON COLUMN permission.perm_name IS '权限名称';
COMMENT ON COLUMN permission.resource_path IS '资源路径';
COMMENT ON COLUMN permission.action IS '操作类型 查询/新增/修改/删除';
COMMENT ON COLUMN permission.description IS '描述';

-- 4. 商品分类表（自引用）
CREATE TABLE category (
    id          NUMBER(11)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   NUMBER(11),
    name        VARCHAR2(100)   NOT NULL,
    level       NUMBER(1)       NOT NULL,
    sort_order  NUMBER(11)      DEFAULT 0 NOT NULL,
    status      NUMBER(1)       DEFAULT 1 NOT NULL,
    icon_url    VARCHAR2(500),
    CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES category(id) ON DELETE SET NULL
);
CREATE INDEX idx_category_parent ON category(parent_id);
COMMENT ON TABLE category IS '商品分类表';
COMMENT ON COLUMN category.id IS '分类ID';
COMMENT ON COLUMN category.parent_id IS '父分类ID（根节点为NULL）';
COMMENT ON COLUMN category.name IS '分类名称';
COMMENT ON COLUMN category.level IS '层级 1=一级 2=二级...';
COMMENT ON COLUMN category.sort_order IS '排序序号（小靠前）';
COMMENT ON COLUMN category.status IS '状态 0=禁用 1=启用';
COMMENT ON COLUMN category.icon_url IS '分类图标URL';

-- 5. 优惠券模板表
CREATE TABLE coupon_template (
    id              NUMBER(11)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(100)   NOT NULL,
    type            NUMBER(1)       NOT NULL,
    amount          NUMBER(10,2)    NOT NULL,
    min_amount      NUMBER(10,2)    NOT NULL,
    total_count     NUMBER(11)      DEFAULT -1 NOT NULL,
    received_count  NUMBER(11)      DEFAULT 0 NOT NULL,
    start_time      DATE            NOT NULL,
    end_time        DATE            NOT NULL,
    status          NUMBER(1)       DEFAULT 1 NOT NULL
);
COMMENT ON TABLE coupon_template IS '优惠券模板表';
COMMENT ON COLUMN coupon_template.id IS '券模板ID';
COMMENT ON COLUMN coupon_template.name IS '优惠券名称';
COMMENT ON COLUMN coupon_template.type IS '类型 1=满减券 2=折扣券';
COMMENT ON COLUMN coupon_template.amount IS '面值或折扣率（折扣券如0.85）';
COMMENT ON COLUMN coupon_template.min_amount IS '最低消费门槛';
COMMENT ON COLUMN coupon_template.total_count IS '发行总量（-1=不限量）';
COMMENT ON COLUMN coupon_template.received_count IS '已领取数量';
COMMENT ON COLUMN coupon_template.start_time IS '有效期开始';
COMMENT ON COLUMN coupon_template.end_time IS '有效期结束';
COMMENT ON COLUMN coupon_template.status IS '状态 0=停用 1=启用';

-- 6. 收货地址表
CREATE TABLE address (
    id              NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER(20)      NOT NULL,
    receiver_name   VARCHAR2(50)    NOT NULL,
    receiver_phone  VARCHAR2(20)    NOT NULL,
    province        VARCHAR2(50)    NOT NULL,
    city            VARCHAR2(50)    NOT NULL,
    district        VARCHAR2(50)    NOT NULL,
    detail_address  VARCHAR2(500)   NOT NULL,
    is_default      NUMBER(1)       DEFAULT 0 NOT NULL,
    created_at      DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_address_user FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE
);
CREATE INDEX idx_address_user ON address(user_id);
COMMENT ON TABLE address IS '收货地址表';
COMMENT ON COLUMN address.id IS '地址ID';
COMMENT ON COLUMN address.user_id IS '用户ID';
COMMENT ON COLUMN address.receiver_name IS '收货人姓名';
COMMENT ON COLUMN address.receiver_phone IS '收货人手机号';
COMMENT ON COLUMN address.province IS '省';
COMMENT ON COLUMN address.city IS '市';
COMMENT ON COLUMN address.district IS '区/县';
COMMENT ON COLUMN address.detail_address IS '详细地址';
COMMENT ON COLUMN address.is_default IS '是否默认 0=否 1=是';
COMMENT ON COLUMN address.created_at IS '创建时间';

-- 7. 商品主表
CREATE TABLE product (
    id              NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id     NUMBER(11)      NOT NULL,
    name            VARCHAR2(200)   NOT NULL,
    description     CLOB,
    main_image      VARCHAR2(500)   NOT NULL,
    status          NUMBER(1)       DEFAULT 1 NOT NULL,
    price_min       NUMBER(10,2)    DEFAULT 0 NOT NULL,
    sales_count     NUMBER(11)      DEFAULT 0 NOT NULL,
    view_count      NUMBER(11)      DEFAULT 0 NOT NULL,
    avg_rating      NUMBER(3,2)     DEFAULT 0 NOT NULL,
    created_at      DATE            DEFAULT SYSDATE NOT NULL,
    updated_at      DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category(id)
);
CREATE INDEX idx_product_category ON product(category_id);
COMMENT ON TABLE product IS '商品主表';
COMMENT ON COLUMN product.id IS '商品ID';
COMMENT ON COLUMN product.category_id IS '分类ID';
COMMENT ON COLUMN product.name IS '商品名称';
COMMENT ON COLUMN product.description IS '商品描述';
COMMENT ON COLUMN product.main_image IS '主图URL';
COMMENT ON COLUMN product.status IS '上架状态 0=下架 1=上架 2=预售';
COMMENT ON COLUMN product.price_min IS '最低售价（冗余）';
COMMENT ON COLUMN product.sales_count IS '累计销量';
COMMENT ON COLUMN product.view_count IS '浏览量';
COMMENT ON COLUMN product.avg_rating IS '评分均值';
COMMENT ON COLUMN product.created_at IS '创建时间';
COMMENT ON COLUMN product.updated_at IS '更新时间';

-- 触发器：自动更新 product.updated_at
CREATE OR REPLACE TRIGGER trg_product_updated
    BEFORE UPDATE ON product
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;
/

-- 8. 商品图片表
CREATE TABLE product_image (
    id          NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  NUMBER(20)      NOT NULL,
    image_url   VARCHAR2(500)   NOT NULL,
    sort_order  NUMBER(11)      DEFAULT 0 NOT NULL,
    created_at  DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_product_image_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE
);
CREATE INDEX idx_product_image_product ON product_image(product_id);
COMMENT ON TABLE product_image IS '商品图片表';
COMMENT ON COLUMN product_image.id IS '图片ID';
COMMENT ON COLUMN product_image.product_id IS '商品ID';
COMMENT ON COLUMN product_image.image_url IS '图片URL';
COMMENT ON COLUMN product_image.sort_order IS '排序序号';
COMMENT ON COLUMN product_image.created_at IS '创建时间';

-- 9. 商品规格表
CREATE TABLE product_spec (
    id          NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  NUMBER(20)      NOT NULL,
    spec_name   VARCHAR2(100)   NOT NULL,
    spec_value  VARCHAR2(200)   NOT NULL,
    sort_order  NUMBER(11),
    CONSTRAINT fk_product_spec_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE
);
CREATE INDEX idx_product_spec_product ON product_spec(product_id);
COMMENT ON TABLE product_spec IS '商品规格表';
COMMENT ON COLUMN product_spec.id IS '规格ID';
COMMENT ON COLUMN product_spec.product_id IS '商品ID';
COMMENT ON COLUMN product_spec.spec_name IS '规格名称（如颜色）';
COMMENT ON COLUMN product_spec.spec_value IS '规格值（如红色）';
COMMENT ON COLUMN product_spec.sort_order IS '排序序号';

-- 10. SKU表
CREATE TABLE sku (
    id              NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      NUMBER(20)      NOT NULL,
    spec_desc       VARCHAR2(500)   NOT NULL,
    price           NUMBER(10,2)    NOT NULL,
    original_price  NUMBER(10,2),
    stock           NUMBER(11)      DEFAULT 0 NOT NULL,
    locked_stock    NUMBER(11)      DEFAULT 0 NOT NULL,
    warning_stock   NUMBER(11)      DEFAULT 0 NOT NULL,
    sku_image       VARCHAR2(500),
    status          NUMBER(1)       DEFAULT 1 NOT NULL,
    CONSTRAINT fk_sku_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE
);
CREATE INDEX idx_sku_product ON sku(product_id);
COMMENT ON TABLE sku IS '商品SKU表';
COMMENT ON COLUMN sku.id IS 'SKU ID';
COMMENT ON COLUMN sku.product_id IS '商品ID';
COMMENT ON COLUMN sku.spec_desc IS '规格描述（如颜色-红/尺码-M）';
COMMENT ON COLUMN sku.price IS '售价';
COMMENT ON COLUMN sku.original_price IS '原价（划线价）';
COMMENT ON COLUMN sku.stock IS '实际库存';
COMMENT ON COLUMN sku.locked_stock IS '锁定库存';
COMMENT ON COLUMN sku.warning_stock IS '预警库存阈值';
COMMENT ON COLUMN sku.sku_image IS 'SKU图片URL';
COMMENT ON COLUMN sku.status IS '状态 0=停售 1=在售';

-- 11. 库存变动日志表
CREATE TABLE inventory_log (
    id            NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id        NUMBER(20)      NOT NULL,
    change_type   VARCHAR2(30)    NOT NULL,
    change_qty    NUMBER(11)      NOT NULL,
    before_stock  NUMBER(11)      NOT NULL,
    after_stock   NUMBER(11)      NOT NULL,
    operator_id   NUMBER(20),
    ref_order_id  NUMBER(20),
    remark        VARCHAR2(500),
    created_at    DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_inventory_log_sku FOREIGN KEY (sku_id) REFERENCES sku(id),
    CONSTRAINT fk_inventory_log_operator FOREIGN KEY (operator_id) REFERENCES "user"(id) ON DELETE SET NULL
);
CREATE INDEX idx_inventory_log_sku ON inventory_log(sku_id);
CREATE INDEX idx_inventory_log_operator ON inventory_log(operator_id);
COMMENT ON TABLE inventory_log IS '库存变动日志表';
COMMENT ON COLUMN inventory_log.id IS '日志ID';
COMMENT ON COLUMN inventory_log.sku_id IS 'SKU ID';
COMMENT ON COLUMN inventory_log.change_type IS '变动类型 SALE=销售扣减 CANCEL=取消回滚 RESTOCK=补货入库 ADJUST=人工调整';
COMMENT ON COLUMN inventory_log.change_qty IS '变动数量（正入库 负出库）';
COMMENT ON COLUMN inventory_log.before_stock IS '变动前库存';
COMMENT ON COLUMN inventory_log.after_stock IS '变动后库存';
COMMENT ON COLUMN inventory_log.operator_id IS '操作人ID';
COMMENT ON COLUMN inventory_log.ref_order_id IS '关联订单ID';
COMMENT ON COLUMN inventory_log.remark IS '备注';
COMMENT ON COLUMN inventory_log.created_at IS '操作时间';

-- 12. 购物车表
CREATE TABLE cart (
    id          NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     NUMBER(20)      NOT NULL,
    sku_id      NUMBER(20)      NOT NULL,
    quantity    NUMBER(11)      DEFAULT 1 NOT NULL,
    selected    NUMBER(1)       DEFAULT 1 NOT NULL,
    created_at  DATE            DEFAULT SYSDATE NOT NULL,
    updated_at  DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    CONSTRAINT fk_cart_sku FOREIGN KEY (sku_id) REFERENCES sku(id)
);
CREATE INDEX idx_cart_user ON cart(user_id);
CREATE INDEX idx_cart_sku ON cart(sku_id);
COMMENT ON TABLE cart IS '购物车表';
COMMENT ON COLUMN cart.id IS '购物车ID';
COMMENT ON COLUMN cart.user_id IS '用户ID';
COMMENT ON COLUMN cart.sku_id IS 'SKU ID';
COMMENT ON COLUMN cart.quantity IS '数量';
COMMENT ON COLUMN cart.selected IS '是否选中 0=未勾选 1=已勾选';
COMMENT ON COLUMN cart.created_at IS '加入时间';
COMMENT ON COLUMN cart.updated_at IS '更新时间';

CREATE OR REPLACE TRIGGER trg_cart_updated
    BEFORE UPDATE ON cart
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;
/

-- 13. 用户角色关联表
CREATE TABLE user_role (
    id          NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     NUMBER(20)      NOT NULL,
    role_id     NUMBER(11)      NOT NULL,
    assigned_at DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE CASCADE,
    CONSTRAINT uk_user_role UNIQUE (user_id, role_id)
);
CREATE INDEX idx_user_role_role ON user_role(role_id);
COMMENT ON TABLE user_role IS '用户角色关联表';
COMMENT ON COLUMN user_role.id IS '主键';
COMMENT ON COLUMN user_role.user_id IS '用户ID';
COMMENT ON COLUMN user_role.role_id IS '角色ID';
COMMENT ON COLUMN user_role.assigned_at IS '分配时间';

-- 14. 角色权限关联表
CREATE TABLE role_permission (
    id            NUMBER(11)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id       NUMBER(11)      NOT NULL,
    permission_id NUMBER(11)      NOT NULL,
    created_at    DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permission_perm FOREIGN KEY (permission_id) REFERENCES permission(id) ON DELETE CASCADE,
    CONSTRAINT uk_role_permission UNIQUE (role_id, permission_id)
);
CREATE INDEX idx_role_permission_perm ON role_permission(permission_id);
COMMENT ON TABLE role_permission IS '角色权限关联表';
COMMENT ON COLUMN role_permission.id IS '主键';
COMMENT ON COLUMN role_permission.role_id IS '角色ID';
COMMENT ON COLUMN role_permission.permission_id IS '权限ID';
COMMENT ON COLUMN role_permission.created_at IS '创建时间';

-- 15. 用户优惠券表
CREATE TABLE user_coupon (
    id                  NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             NUMBER(20)      NOT NULL,
    coupon_template_id  NUMBER(11)      NOT NULL,
    status              NUMBER(1)       DEFAULT 0 NOT NULL,
    received_at         DATE            DEFAULT SYSDATE NOT NULL,
    used_at             DATE,
    order_id            NUMBER(20),
    CONSTRAINT fk_user_coupon_user FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_coupon_template FOREIGN KEY (coupon_template_id) REFERENCES coupon_template(id)
);
CREATE INDEX idx_user_coupon_user ON user_coupon(user_id);
CREATE INDEX idx_user_coupon_template ON user_coupon(coupon_template_id);
COMMENT ON TABLE user_coupon IS '用户优惠券表';
COMMENT ON COLUMN user_coupon.id IS '领取ID';
COMMENT ON COLUMN user_coupon.user_id IS '用户ID';
COMMENT ON COLUMN user_coupon.coupon_template_id IS '券模板ID';
COMMENT ON COLUMN user_coupon.status IS '使用状态 0=未使用 1=已使用 2=已过期';
COMMENT ON COLUMN user_coupon.received_at IS '领取时间';
COMMENT ON COLUMN user_coupon.used_at IS '使用时间';
COMMENT ON COLUMN user_coupon.order_id IS '关联订单ID（使用时填写）';

-- 16. 订单主表
CREATE TABLE order_main (
    id                NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no          VARCHAR2(32)    NOT NULL,
    user_id           NUMBER(20)      NOT NULL,
    address_id        NUMBER(20)      NOT NULL,
    user_coupon_id    NUMBER(20),
    status            NUMBER(1)       DEFAULT 0 NOT NULL,
    total_amount      NUMBER(10,2)    NOT NULL,
    discount_amount   NUMBER(10,2)    DEFAULT 0 NOT NULL,
    pay_amount        NUMBER(10,2)    NOT NULL,
    pay_expire_time   DATE            NOT NULL,
    receiver_snapshot VARCHAR2(500)   NOT NULL,
    remark            VARCHAR2(500),
    created_at        DATE            DEFAULT SYSDATE NOT NULL,
    updated_at        DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES "user"(id),
    CONSTRAINT fk_order_address FOREIGN KEY (address_id) REFERENCES address(id),
    CONSTRAINT fk_order_coupon FOREIGN KEY (user_coupon_id) REFERENCES user_coupon(id) ON DELETE SET NULL,
    CONSTRAINT uk_order_no UNIQUE (order_no)
);
CREATE INDEX idx_order_user ON order_main(user_id);
CREATE INDEX idx_order_address ON order_main(address_id);
CREATE INDEX idx_order_coupon ON order_main(user_coupon_id);
CREATE INDEX idx_order_status_created ON order_main(status, created_at);
COMMENT ON TABLE order_main IS '订单主表';
COMMENT ON COLUMN order_main.id IS '订单ID';
COMMENT ON COLUMN order_main.order_no IS '订单编号';
COMMENT ON COLUMN order_main.user_id IS '用户ID';
COMMENT ON COLUMN order_main.address_id IS '收货地址ID';
COMMENT ON COLUMN order_main.user_coupon_id IS '优惠券领取ID';
COMMENT ON COLUMN order_main.status IS '订单状态 0=待支付 1=已支付 2=已发货 3=已完成 4=已取消';
COMMENT ON COLUMN order_main.total_amount IS '商品总额';
COMMENT ON COLUMN order_main.discount_amount IS '优惠金额';
COMMENT ON COLUMN order_main.pay_amount IS '实付金额';
COMMENT ON COLUMN order_main.pay_expire_time IS '支付超时时间';
COMMENT ON COLUMN order_main.receiver_snapshot IS '收货人快照（JSON）';
COMMENT ON COLUMN order_main.remark IS '买家备注';
COMMENT ON COLUMN order_main.created_at IS '创建时间';
COMMENT ON COLUMN order_main.updated_at IS '更新时间';

CREATE OR REPLACE TRIGGER trg_order_updated
    BEFORE UPDATE ON order_main
    FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;
/

-- 17. 订单明细表
CREATE TABLE order_item (
    id                 NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id           NUMBER(20)      NOT NULL,
    sku_id             NUMBER(20)      NOT NULL,
    product_name_snap  VARCHAR2(200)   NOT NULL,
    spec_snap          VARCHAR2(500)   NOT NULL,
    main_image_snap    VARCHAR2(500)   NOT NULL,
    unit_price         NUMBER(10,2)    NOT NULL,
    quantity           NUMBER(11)      NOT NULL,
    subtotal           NUMBER(10,2)    NOT NULL,
    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES order_main(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_item_sku FOREIGN KEY (sku_id) REFERENCES sku(id)
);
CREATE INDEX idx_order_item_order ON order_item(order_id);
CREATE INDEX idx_order_item_sku ON order_item(sku_id);
COMMENT ON TABLE order_item IS '订单明细表';
COMMENT ON COLUMN order_item.id IS '明细ID';
COMMENT ON COLUMN order_item.order_id IS '订单ID';
COMMENT ON COLUMN order_item.sku_id IS 'SKU ID';
COMMENT ON COLUMN order_item.product_name_snap IS '商品名称快照';
COMMENT ON COLUMN order_item.spec_snap IS '规格快照';
COMMENT ON COLUMN order_item.main_image_snap IS '商品主图快照';
COMMENT ON COLUMN order_item.unit_price IS '下单单价快照';
COMMENT ON COLUMN order_item.quantity IS '购买数量';
COMMENT ON COLUMN order_item.subtotal IS '小计金额';

-- 18. 订单状态日志表
CREATE TABLE order_log (
    id          NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    NUMBER(20)      NOT NULL,
    from_status NUMBER(1)       NOT NULL,
    to_status   NUMBER(1)       NOT NULL,
    operator_id NUMBER(20),
    remark      VARCHAR2(200),
    created_at  DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_order_log_order FOREIGN KEY (order_id) REFERENCES order_main(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_log_operator FOREIGN KEY (operator_id) REFERENCES "user"(id) ON DELETE SET NULL
);
CREATE INDEX idx_order_log_order ON order_log(order_id);
CREATE INDEX idx_order_log_operator ON order_log(operator_id);
COMMENT ON TABLE order_log IS '订单状态日志表';
COMMENT ON COLUMN order_log.id IS '日志ID';
COMMENT ON COLUMN order_log.order_id IS '订单ID';
COMMENT ON COLUMN order_log.from_status IS '变更前状态';
COMMENT ON COLUMN order_log.to_status IS '变更后状态';
COMMENT ON COLUMN order_log.operator_id IS '操作人ID';
COMMENT ON COLUMN order_log.remark IS '备注';
COMMENT ON COLUMN order_log.created_at IS '变更时间';

-- 19. 支付记录表
CREATE TABLE payment (
    id            NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      NUMBER(20)      NOT NULL,
    pay_method    VARCHAR2(30)    NOT NULL,
    status        NUMBER(1)       DEFAULT 0 NOT NULL,
    trade_no      VARCHAR2(100),
    pay_amount    NUMBER(10,2)    NOT NULL,
    paid_at       DATE,
    callback_data CLOB,
    CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES order_main(id) ON DELETE CASCADE,
    CONSTRAINT uk_payment_order UNIQUE (order_id),
    CONSTRAINT uk_payment_trade_no UNIQUE (trade_no)
);
COMMENT ON TABLE payment IS '支付记录表';
COMMENT ON COLUMN payment.id IS '支付ID';
COMMENT ON COLUMN payment.order_id IS '订单ID';
COMMENT ON COLUMN payment.pay_method IS '支付方式';
COMMENT ON COLUMN payment.status IS '支付状态 0=待支付 1=支付成功 2=支付失败 3=已退款';
COMMENT ON COLUMN payment.trade_no IS '第三方交易流水号';
COMMENT ON COLUMN payment.pay_amount IS '实付金额';
COMMENT ON COLUMN payment.paid_at IS '支付时间';
COMMENT ON COLUMN payment.callback_data IS '回调原始数据';

-- 20. 物流信息表（单仓发货）
CREATE TABLE logistics (
    id           NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     NUMBER(20)      NOT NULL,
    company_name VARCHAR2(100)   NOT NULL,
    tracking_no  VARCHAR2(100)   NOT NULL,
    shipped_at   DATE            NOT NULL,
    status       NUMBER(1)       DEFAULT 0 NOT NULL,
    CONSTRAINT fk_logistics_order FOREIGN KEY (order_id) REFERENCES order_main(id) ON DELETE CASCADE,
    CONSTRAINT uk_logistics_order UNIQUE (order_id),
    CONSTRAINT uk_logistics_tracking UNIQUE (tracking_no)
);
COMMENT ON TABLE logistics IS '物流信息表';
COMMENT ON COLUMN logistics.id IS '物流ID';
COMMENT ON COLUMN logistics.order_id IS '订单ID';
COMMENT ON COLUMN logistics.company_name IS '物流公司名称';
COMMENT ON COLUMN logistics.tracking_no IS '运单号';
COMMENT ON COLUMN logistics.shipped_at IS '发货时间';
COMMENT ON COLUMN logistics.status IS '物流状态 0=已揽件 1=运输中 2=派件中 3=已签收';

-- 21. 物流轨迹表
CREATE TABLE logistics_track (
    id           NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logistics_id NUMBER(20)      NOT NULL,
    track_desc   VARCHAR2(500)   NOT NULL,
    track_time   DATE            NOT NULL,
    location     VARCHAR2(200),
    CONSTRAINT fk_track_logistics FOREIGN KEY (logistics_id) REFERENCES logistics(id) ON DELETE CASCADE
);
CREATE INDEX idx_track_logistics ON logistics_track(logistics_id);
COMMENT ON TABLE logistics_track IS '物流轨迹表';
COMMENT ON COLUMN logistics_track.id IS '轨迹ID';
COMMENT ON COLUMN logistics_track.logistics_id IS '物流ID';
COMMENT ON COLUMN logistics_track.track_desc IS '轨迹描述';
COMMENT ON COLUMN logistics_track.track_time IS '轨迹时间';
COMMENT ON COLUMN logistics_track.location IS '所在地';

-- 22. 商品评价表
CREATE TABLE review (
    id            NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      NUMBER(20)      NOT NULL,
    product_id    NUMBER(20)      NOT NULL,
    user_id       NUMBER(20)      NOT NULL,
    rating        NUMBER(1)       NOT NULL,
    content       CLOB,
    images        VARCHAR2(2000),
    is_anonymous  NUMBER(1)       DEFAULT 0 NOT NULL,
    status        NUMBER(1)       DEFAULT 1 NOT NULL,
    created_at    DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_review_order FOREIGN KEY (order_id) REFERENCES order_main(id),
    CONSTRAINT fk_review_product FOREIGN KEY (product_id) REFERENCES product(id),
    CONSTRAINT fk_review_user FOREIGN KEY (user_id) REFERENCES "user"(id)
);
CREATE INDEX idx_review_order ON review(order_id);
CREATE INDEX idx_review_product ON review(product_id);
CREATE INDEX idx_review_user ON review(user_id);
COMMENT ON TABLE review IS '商品评价表';
COMMENT ON COLUMN review.id IS '评价ID';
COMMENT ON COLUMN review.order_id IS '订单ID';
COMMENT ON COLUMN review.product_id IS '商品ID';
COMMENT ON COLUMN review.user_id IS '用户ID';
COMMENT ON COLUMN review.rating IS '评分 1-5星';
COMMENT ON COLUMN review.content IS '评价内容';
COMMENT ON COLUMN review.images IS '评价图片URL列表（JSON数组）';
COMMENT ON COLUMN review.is_anonymous IS '是否匿名 0=显示用户名 1=匿名';
COMMENT ON COLUMN review.status IS '状态 0=审核中 1=已发布 2=已屏蔽';
COMMENT ON COLUMN review.created_at IS '评价时间';

-- 23. 操作日志表
CREATE TABLE operation_log (
    id              NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id     NUMBER(20)      NOT NULL,
    operator_name   VARCHAR2(50)    NOT NULL,
    module          VARCHAR2(50)    NOT NULL,
    action          VARCHAR2(100)   NOT NULL,
    description     CLOB,
    ip_address      VARCHAR2(50)    NOT NULL,
    request_params  CLOB,
    result          NUMBER(1)       NOT NULL,
    created_at      DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_oplog_operator FOREIGN KEY (operator_id) REFERENCES "user"(id)
);
CREATE INDEX idx_oplog_operator ON operation_log(operator_id);
CREATE INDEX idx_oplog_created ON operation_log(created_at);
COMMENT ON TABLE operation_log IS '操作日志表';
COMMENT ON COLUMN operation_log.id IS '日志ID';
COMMENT ON COLUMN operation_log.operator_id IS '操作员ID';
COMMENT ON COLUMN operation_log.operator_name IS '操作员用户名（冗余）';
COMMENT ON COLUMN operation_log.module IS '操作模块';
COMMENT ON COLUMN operation_log.action IS '操作动作';
COMMENT ON COLUMN operation_log.description IS '操作详情';
COMMENT ON COLUMN operation_log.ip_address IS '操作者IP地址';
COMMENT ON COLUMN operation_log.request_params IS '请求参数（脱敏后JSON）';
COMMENT ON COLUMN operation_log.result IS '操作结果 0=失败 1=成功';
COMMENT ON COLUMN operation_log.created_at IS '操作时间';

-- 24. 订单统计快照表
CREATE TABLE order_stat_snapshot (
    id               NUMBER(11)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stat_date        DATE            NOT NULL,
    order_count      NUMBER(11)      DEFAULT 0 NOT NULL,
    paid_count       NUMBER(11)      DEFAULT 0 NOT NULL,
    sales_amount     NUMBER(12,2)    DEFAULT 0 NOT NULL,
    refund_amount    NUMBER(12,2)    DEFAULT 0 NOT NULL,
    avg_order_amount NUMBER(10,2)    DEFAULT 0 NOT NULL,
    new_user_count   NUMBER(11)      DEFAULT 0 NOT NULL,
    CONSTRAINT uk_stat_date UNIQUE (stat_date)
);
COMMENT ON TABLE order_stat_snapshot IS '订单统计快照表';
COMMENT ON COLUMN order_stat_snapshot.id IS 'ID';
COMMENT ON COLUMN order_stat_snapshot.stat_date IS '统计日期';
COMMENT ON COLUMN order_stat_snapshot.order_count IS '当日订单总数';
COMMENT ON COLUMN order_stat_snapshot.paid_count IS '当日已支付订单数';
COMMENT ON COLUMN order_stat_snapshot.sales_amount IS '当日销售额';
COMMENT ON COLUMN order_stat_snapshot.refund_amount IS '当日退款金额';
COMMENT ON COLUMN order_stat_snapshot.avg_order_amount IS '客单价';
COMMENT ON COLUMN order_stat_snapshot.new_user_count IS '当日新增用户数';

-- ======================================================
-- 基础数据初始化（文档要求：角色表初始三条记录）
-- ======================================================
INSERT INTO role (role_name, description) VALUES ('USER', '普通用户');
INSERT INTO role (role_name, description) VALUES ('SERVICE', '客服');
INSERT INTO role (role_name, description) VALUES ('ADMIN', '管理员');

COMMIT;
